version: "3.7"
services:
    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www
        ports:
            - "8081:80"
    php-fpm:
        container_name: php
        build:
            context: ./docker/php-fpm
        depends_on:
            - postgres
        volumes:
            - ./:/var/www
    postgres:
        container_name: postgres
        image: postgres:11.2-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
volumes:
    postgres: