version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8081:80"
  php-fpm:
    container_name: php
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    volumes:
      - ./docker/databases:/docker-entrypoint-initdb.d
      - "./mysql:/var/lib/mysql"
    ports:
      - "8989:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=local