#api.registration:
#    path: /api/register
#    controller: App\Controller\Auth\SignUpController::index
#    methods: POST
#api.confirm:
#    path: /api/confirm-registration
#    controller: App\Controller\Auth\ConfirmRegistrationController::index
#    methods: POST
